### ISSUE TITLE
Unable to change speed of cursor in 1.05.003

### ISSUE THREAD

**Issue by imno1234** [neatdecisions/neatmouse#7]
I'm win10 64bit user.
Change in speed of cursor (including alt. speed) does not work in 1.05.003 while 1.05.002 works well in my computer.
Maybe the recent change in setting processing cause this issue.

**Comment by neatdecisions** [comment]
Thank you for the report! The fix is underway.

**Comment by neatdecisions** [comment]
Fixed in [v1.05.004](https://github.com/neatdecisions/neatmouse/releases/tag/v1.05.004).
